=begin
#Webhooks

#Sends notifications on trigger events to subscribed observers

The version of the OpenAPI document: 2.0.119-SNAPSHOT

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for LeanixWebhooksApi::EventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EventsApi' do
  before do
    # run before each test
    @api_instance = LeanixWebhooksApi::EventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EventsApi' do
    it 'should create an instance of EventsApi' do
      expect(@api_instance).to be_instance_of(LeanixWebhooksApi::EventsApi)
    end
  end

  # unit tests for create_event
  # createEvent
  # Endpoint to trigger an event.
  # @param event the event to trigger
  # @param [Hash] opts the optional parameters
  # @return [EventResponse]
  describe 'create_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_event_batch
  # createEventBatch
  # Endpoint to trigger multiple events.
  # @param batch the events to trigger
  # @param [Hash] opts the optional parameters
  # @return [EventListResponse]
  describe 'create_event_batch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
