=begin
#Webhooks

#Sends notifications on trigger events to subscribed observers

The version of the OpenAPI document: 2.0.119-SNAPSHOT

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixWebhooksApi::Cursor
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixWebhooksApi::Cursor do
  let(:instance) { LeanixWebhooksApi::Cursor.new }

  describe 'test an instance of Cursor' do
    it 'should create an instance of Cursor' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixWebhooksApi::Cursor)
    end
  end

  describe 'test attribute "offset"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
