=begin
#Webhooks

#Sends notifications on trigger events to subscribed observers

The version of the OpenAPI document: 2.0.119-SNAPSHOT

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

# Common files
require 'leanix_webhooks_api/api_client'
require 'leanix_webhooks_api/api_error'
require 'leanix_webhooks_api/version'
require 'leanix_webhooks_api/configuration'

# Models
require 'leanix_webhooks_api/models/api_error'
require 'leanix_webhooks_api/models/basic_response'
require 'leanix_webhooks_api/models/cursor'
require 'leanix_webhooks_api/models/delivery'
require 'leanix_webhooks_api/models/delivery_list_response'
require 'leanix_webhooks_api/models/event'
require 'leanix_webhooks_api/models/event_batch'
require 'leanix_webhooks_api/models/event_list_response'
require 'leanix_webhooks_api/models/event_response'
require 'leanix_webhooks_api/models/pull_event'
require 'leanix_webhooks_api/models/pull_result'
require 'leanix_webhooks_api/models/pull_result_response'
require 'leanix_webhooks_api/models/subscription'
require 'leanix_webhooks_api/models/subscription_list_response'
require 'leanix_webhooks_api/models/subscription_response'

# APIs
require 'leanix_webhooks_api/api/events_api'
require 'leanix_webhooks_api/api/subscriptions_api'

module LeanixWebhooksApi
  class << self
    # Customize default settings for the SDK using block.
    #   LeanixWebhooksApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
